# Site settings
title: Tyler Heshka
description: > # this means to ignore newlines until "baseurl:"
  I'm Tyler, an Autodidact Graphic Designer, Web Developer,
  and Entrepreneur from Canada!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://theshka.gitub.io" # the base hostname & protocol for your site
github_username:  theshka

# Build settings
timezone: America/Regina
markdown: kramdown
